[project]
name = "ymcirc"
version = "0.1.0"
description = "Circuit Hamiltonians for SU(3) lattice gauge theory"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "matplotlib~=3.9",
    "matplotlib-label-lines~=0.7.0",
    "numpy~=2.1",
    "pandas~=2.2",
    "pylatexenc~=2.10",
    "qiskit~=2.1",
    "qiskit-aer~=0.17",
    "qiskit-qasm3-import~=0.6",
    "scipy~=1.14",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
